Update updaetable.yml

diff --git a/.github/workflows/updaetable.yml b/.github/workflows/updaetable.yml
--- a/.github/workflows/updaetable.yml
+++ b/.github/workflows/updaetable.yml
@@ -34,7 +34,18 @@ jobs:
           echo "::set-output name=a::$a"
           echo "::set-output name=b::$b"
 
-      
+      - name: Delete upddata.txt file if exists
+        run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+          if [ -f "upddata.txt" ]; then
+            git f- rm upddata.txt
+            git commit -m "Delete upddata.txt" || echo "Nothing to delete"
+            git push origin main || echo "Failed to push deletion commit"
+          else
+            echo "upddata.txt file not found. Skipping deletion."
+          fi 
+          
       - name: Rename newdata.txt to upddata.txt
         run: |
           mv newdata.txt upddata.txt
