Update updaetable.yml

diff --git a/.github/workflows/updaetable.yml b/.github/workflows/updaetable.yml
--- a/.github/workflows/updaetable.yml
+++ b/.github/workflows/updaetable.yml
@@ -39,6 +39,18 @@ jobs:
           git config --global user.name "sandeephallimane"
           git config --global user.email "hssandp@gmail.com"
           
+      - name: Delete upddata.txt file if exists
+        run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+          if [ -f "upddata.txt" ]; then
+            git rm upddata.txt
+            git commit -m "Delete upddata.txt" || echo "Nothing to delete"
+            git push origin main || echo "Failed to push deletion commit"
+          else
+            echo "upddata.txt file not found. Skipping deletion."
+          fi   
+          
       - name: Pull latest changes
         run: git pull --rebase origin main
 
